# Generated by Django 4.2 on 2023-04-12 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appProyectos', '0002_alter_cliente_telefono_alter_empleado_telefono'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Proyectos',
            new_name='Proyecto',
        ),
    ]
