# Generated by Django 4.2 on 2023-04-12 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appProyectos', '0003_rename_proyectos_proyecto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='tarea_realizar',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='tarea_realizar',
            field=models.ManyToManyField(to='appProyectos.tarea'),
        ),
    ]
