# Generated by Django 4.1.7 on 2023-04-17 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appProyectos', '0004_remove_proyecto_tarea_realizar_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyecto',
            old_name='tarea_realizar',
            new_name='tareas',
        ),
        migrations.RenameField(
            model_name='tarea',
            old_name='estado_tarea',
            new_name='estado',
        ),
    ]
