# Generated by Django 4.1.7 on 2023-04-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appProyectos', '0008_alter_cliente_telefono_alter_empleado_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='notas',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
