# Generated by Django 4.1.7 on 2023-04-18 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appProyectos', '0009_alter_tarea_notas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='presupuesto',
            field=models.FloatField(),
        ),
    ]
