# Generated by Django 4.1.7 on 2023-04-18 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appProyectos', '0010_alter_proyecto_presupuesto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='tareas',
        ),
        migrations.AddField(
            model_name='tarea',
            name='proyecto',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='appProyectos.proyecto'),
            preserve_default=False,
        ),
    ]
